name: Container

on:
  push:
    branches:
      - main
    tags:        
      - "*"
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_NAME: ${{ github.repository }}
  CONTAINER_LOGIN: ${{ github.actor }}
  CONTAINER_PASS: ${{ secrets.GITHUB_TOKEN }}

jobs:
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
  build-push-image:
    runs-on: ubuntu-latest
    needs: 
      - validate-wrapper
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17.0"
          distribution: "temurin"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and publish container image (tagged)
        if: github.ref_type == 'tag'
        run: ./gradlew bootBuildImage --publishImage
        env:
          CONTAINER_VERSION: ${{ github.ref_name }}
      - name: Build and publish container image (latest)
        run: ./gradlew bootBuildImage --publishImage
        env:
          CONTAINER_VERSION: nightly
